%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data:  [1607.8386905, 0., 626.81507,
           0.,  1607.8386905, 437.723567, 
           0.,  0., 1.]

DistCoeffs: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [-0.039993213306442683, -0.13509302045878691, 0.010227824337537413, -4.7528610260453942e-05,  -0.]
  
# ExtrinsicMat: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [0,0,1, 0.04, 
#          -1, 0, 0,0.05, 
#           0, -1, 0,-0.03, 
#           0.0, 0.0, 0.0, 1.0]

# ExtrinsicMat: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [0,-1,0, 0.05, 
#          0, 0, -1,-0.03, 
#           1, 0, 0,-0.04, 
#           0.0, 0.0, 0.0, 1.0]

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [1.0,0.0,0.0, 0.05, 
         0.0, 1.0, 0.0,-0.03, 
          0.0, 0.0, 1.0,-0.04, 
          0.0, 0.0, 0.0, 1.0]

Camera.width: 1296
Camera.height: 972
